  ###################################
  # Music Generation microservice
  ###################################

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  music_generation:
    build: ./music_generation
    restart: always
    ports:
      - "5100:5100"
    depends_on:
      - redis

