  ###################################
  # Music Generation microservice
  ###################################

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  music_generation:
    build: ./music_generation
    restart: always
    ports:
      - "5100:5100"
    depends_on:
      - redis
  img2img:
    build: ./img2img
    ports:
      - "5000:5000"
    volumes:
      - img2img:/img2img
    environment:
      - CHECKPOINT_PATH=${CHECKPOINT_PATH}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_Bucket=${S3_Bucket}

volumes:
  img2img: 
