  ###################################
  # Music Generation microservice
  ###################################

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  music_generation_service:
    image: musicgenerationservice:latest
    ports:
      - "5100:5100"
    volumes:
      - ./assets:/app/assets
    depends_on:
      - redis
    env_file:
      - ./music_generation/.env

