services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
  img2img:
    build: ./img2img
    ports:
      - "5000:5000"
    volumes:
      - img2img:/OOTDiffusion

volumes:
  img2img: 
